# Site
name: "Tim Stock"
title: "azurehero.de"
description: "personal blog from Tim Stock"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  tim: 
    name: tim
    display_name: Tim
    description: "Microsoft Customer Engineer"
    avatar: 'assets/images/TFS_crop.jpg'
    email: tim.stock@kerncloud.net
    twitter: https://twitter.com/wowthemesnet
    github: https://github.com/tistock

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

adsense: "disabled"


# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
